// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/simulation-studio/App.tsx": () => import("../components/mockups/simulation-studio/App.tsx"),
  "./components/mockups/simulation-studio/FacilitatorDashboard.tsx": () => import("../components/mockups/simulation-studio/FacilitatorDashboard.tsx"),
  "./components/mockups/simulation-studio/ModeratorApp.tsx": () => import("../components/mockups/simulation-studio/ModeratorApp.tsx"),
  "./components/mockups/simulation-studio-copy-W8YFiH6Z/App.tsx": () => import("../components/mockups/simulation-studio-copy-W8YFiH6Z/App.tsx"),
  "./components/mockups/simulation-studio-copy-W8YFiH6Z/FacilitatorDashboard.tsx": () => import("../components/mockups/simulation-studio-copy-W8YFiH6Z/FacilitatorDashboard.tsx"),
  "./components/mockups/simulation-studio-copy-W8YFiH6Z/SimulationStudioCopyW8YFiH6Z.tsx": () => import("../components/mockups/simulation-studio-copy-W8YFiH6Z/SimulationStudioCopyW8YFiH6Z.tsx")
};
